#!/usr/bin/env python3

from httplib2 import Http
from urllib.parse import urlencode
import urllib.request
import json
from pprint import PrettyPrinter
import re
import argparse
import sys
import os.path


def get_config(config_file):
    fin = open(config_file)
    config = json.load(fin)
    return(config)

def get_output_filename(programme_data):
    programme_title = ""
    episode_number = ""
    episode_title = ""
    series_title = ""
    filename_extension = ""

    programme_title = re.sub('\s', "_", programme_data['title'])

    if 'episode' in programme_data:
        if 'position' in programme_data['episode']:
            episode_number = programme_data['episode']['position']
        else:
            episode_number = "XX"
        episode_title = re.sub('\s', "_", programme_data['episode']['title'])
    else:
        episode_number = programme_data['uuid']

    if 'series' in programme_data:
        series_title = re.sub('\s', "_", programme_data['series']['title'])
    else:
        series_title = "special"
    
    filename_extension = programme_data['media'][options.media]['ext']

    output_filename = programme_title 

    if not programme_title == series_title:
        output_filename = output_filename + "_-_" + series_title 
    output_filename = output_filename + "_-_Episode_" + str(episode_number).zfill(2) 

    if not (re.match("^episode_[0-9]", episode_title, flags=re.I) or episode_title is ""):
        output_filename = output_filename +"_-_" + episode_title 

    output_filename = output_filename + "." + filename_extension

    return(output_filename)

def get_search_url(show):
    search_string = re.sub("\s", "+", show)
    search_url_stub = "http://devapi.bbcredux.com/search.json?limit=256&sort=date&pname="
    search_url = search_url_stub + search_string
    return search_url

def get_programmes(search_url, date, channel):
    http = create_http_connection()

    resp, content = http.request(search_url)

    if re.match("^4", resp['status']):
        print("Problem searching " + search_url + " Status: " + resp['status'])
        sys.exit(1)
    else:
        data = json.loads(str(content.decode("utf-8")))

    programmes = []
    for programme in data["results"]:
        if date and not (programme["date"] == date):
            continue
        if channel and not (programme["service"] == channel):
            continue
        programmes.append(programme["diskref"])

    programmes.reverse() # puts earliest pisode first
    return(programmes)

def create_http_connection():
    http = Http(".cache")
    http.add_credentials(config['username'], config['password'])
    return(http)

def get_programme_content(programme):
    http = create_http_connection()
    media_url_stub = "http://devapi.bbcredux.com/programme/"
    media_url = media_url_stub + programme + ".json"

    resp, content = http.request(media_url)

    if re.match("^4", resp['status']):
        print("Problem downloading " + media_url + " Status: " + resp['status'])
        sys.exit(1)
    else:
        data = json.loads(str(content.decode("utf-8")))
	
        if options.debug:
            #TODO print out the highlights of the data instead of all of it
            pp = PrettyPrinter(indent=4)
            pp.pprint(data)
	
        if data['type'] == options.type:
            output_filename = get_output_filename(data)
	
            media_uri = data['media'][options.media]['uri']
            if not options.debug:
                print(media_uri + " downloading as " + output_filename)
                try:
                    if options.quiet:
                        urllib.request.urlretrieve(media_uri, output_filename)
                    else:
                        urllib.request.urlretrieve(media_uri, output_filename, reporthook=dlProgress) 
                except ContentTooShortError:
                    print("problem downloading url " + media_uri)
                print("Done")
            else:
                print("Meadia URL: " + media_uri)
                print("Filename:   " + output_filename)
                print()

def dlProgress(count, blockSize, totalSize):
    percent = int(count*blockSize*100/totalSize)
    sys.stdout.write("\r%2d%%\t\t%d / %d" % (percent, count*blockSize, totalSize))
    sys.stdout.flush()

def config_help():
    print(
        """The config file should consist of a JSON file with a hash
        with the username and password. i.e.

        { "username": "myusername", "password": "mypassword" }

        This should be in ~/.get_redux.cfg
        """)

def main():
    default_config_file = os.path.expanduser('~/.get_redux.cfg')
    parser = argparse.ArgumentParser('Download all shows with a show name matching a particular pattern')
    parser.add_argument('-s', '--show', dest="show", required=True, 
                        help="name of the show to be downloaded")
    parser.add_argument('-m', '--media', dest="media", default="mp4-hi", 
                        help="type of file to be downloaded, e.g. mp3, mp4-hi")
    parser.add_argument('-t', '--type', dest="type", default="tv",
                        help="type of show. 'tv' or 'radio'")
    parser.add_argument("-z", "--date", dest="date", default=False,
                        help="date to search on. Format YYYY-MM-DD")
    parser.add_argument('-d', '--debug', action="store_true", default=False)
    parser.add_argument("-c", "--config", dest="config_file", default=default_config_file,
                        help="specify config file. Default: "+default_config_file)
    parser.add_argument('-b', '--channel', dest="channel", default=False)
    parser.add_argument('-q', '--quiet', action="store_true", default=False)
    #parser.add_argument('-l', '--list', action="store_true", default=False)

    global options
    options = parser.parse_args()

    global config
    config = get_config(options.config_file)
    if not "username" in config or not "password" in config:
        config_help()
        sys.exit()

    if options.type == "radio":
        options.media = "mp3"

    if not options.show:
        parser.print_help()
        sys.exit()

    search_url = get_search_url(options.show)
    programmes = get_programmes(search_url, options.date, options.channel)

    if options.debug:
        pp = PrettyPrinter(indent=4)
        pp.pprint(programmes)

    for programme in programmes:
        get_programme_content(programme)
	
if __name__ == "__main__":
    main()

